config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  match 'search_results', to: 'businesses#search_results', via: 'get'

  resources :businesses
  resources :categories do
    resources :businesses
  end

end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :category
  validates_presence_of :name, :phone, :description
  validates :url, format: { with: /(?:http:\/\/|https:\/\/)/,
            message: "%{value} needs to include http:// or https://" }
  validates :url, format: { with: /(?:.com)/,
            message: "%{value} needs to have a domain ending (i.e. '.com')"}
  validates :img, format: { with: /(?:jpg|gif|png)/,
            message: "Images must be one of the formats: '.png', '.jpg', '.jpeg', '.gif'"}
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :businesses

  validates_presence_of :name, :img

  validates :img, format: {with: /(?:jpg|gif|png)/,
            message: "Images must be one of the formats: '.png', '.jpg', '.jpeg', '.gif'"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :destroy, :update]

  def index
    @businesses = Business.all.order(name: :desc)
  end

  def search_results
    if params[:category]
      @businesses = Category.find(params[:category]).businesses.select{ |business| business.name.downcase.include?(params[:search].downcase)}
    else
      @businesses = Business.all.select{ |business| business.name.downcase.include?(params[:search].downcase)}
    end
  end

  def show
  end

  def new
    @business   = Business.new
    @categories = Category.all
  end

  def create
    @business = Business.new(business_params)
    @business.category_id = business_params[:category_id]
    if @business.save
      redirect_to @business
    else
      render :new
    end
  end

  def edit
    @categories = Category.all.order(name: :asc)
  end

  def update
    if @business.update_attributes(business_params)
      redirect_to @business
    else
      render :edit
    end
  end

  def destroy
    @business.delete
    redirect_to businesses_path
  end

  private

    def business_params
      params.require(:business)
        .permit(:name,
                :img,
                :mailing_address,
                :mailing_city,
                :mailing_state,
                :mailing_zip,
                :street_address,
                :street_city,
                :street_state,
                :street_zip,
                :url,
                :phone,
                :fax,
                :description,
                :img,
                :hours_of_operation,
                :category_id)
    end

    def set_business
      @business = Business.find(params[:id])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :update, :destroy, :edit]

  def index
    @categories = Category.all.order(name: :asc)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def destroy
    @category.delete
    redirect_to categories_path
  end

  def edit
  end

  def update

    if @category.update_attributes(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

    def category_params
      params.require(:category).permit(:name, :img)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :mailing_address %>
  <%= f.text_field :mailing_address %>

  <%= f.label :mailing_city %>
  <%= f.text_field :mailing_city %>

  <%= f.label :mailing_state %>
  <%= f.text_field :mailing_state %>

  <%= f.label :mailing_zip %>
  <%= f.text_field :mailing_zip %>

  <%= f.label :street_address %>
  <%= f.text_field :street_address %>

  <%= f.label :street_city %>
  <%= f.text_field :street_city %>

  <%= f.label :street_state %>
  <%= f.text_field :street_state %>

  <%= f.label :street_zip %>
  <%= f.text_field :street_zip %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.label :phone %>
  <%= f.phone_field :phone %>

  <%= f.label :fax %>
  <%= f.phone_field :fax %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :img %>
  <%= f.text_field :img %>

  <%= f.label :hours_of_operation %>
  <%= f.text_field :hours_of_operation %>

  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories, :id, :name %>

  <%= f.submit %>
<% end %>

app/views/businesses/edit.html.erb
<h1><%= @business.name %> | Edit</h1>

<%= render 'form' %>

app/views/businesses/index.html.erb
<h1>Businesses</h1>

<%= link_to 'New', new_business_path %>

<ul>
  <% @businesses.each do |business| %>
    <%= link_to business_path(business) do %>
      <li><%= business.name %></li>
    <% end %>
  <% end %>
</ul>

app/views/businesses/new.html.erb
<h1><%= @business.name %> | New</h1>

<%= render 'form' %>

app/views/businesses/search_results.html.erb
<h1>Results</h1>

<p>
  Your search returned <%= @businesses.count %> results
</p>

<ul>
  <% @businesses.each do |business| %>
    <%= link_to business_path(business) do %>
      <li><%= business.name %></li>
    <% end %>
  <% end %>
</ul>

app/views/businesses/show.html.erb
<h1><%= @business.name %></h1> <%= link_to "edit", edit_business_path %>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :img %>
  <%= f.text_field :img %>

  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Wiki</h1>


<div id="search-box">
  <%= form_tag(search_results_path, :method => 'get') do %>
    <%= text_field_tag :search, params[:search] %>
    <button type="submit" type="button">Search</button>
  <% end %>
</div>


<h2>Categories</h2>
<ul>
  <% @categories.each do |category| %>
    <%= link_to category_path(category) do %>
      <li><%= category.name %></li>
    <% end %>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>Add a new category </h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<div id="search-box">
  Search in <%= @category.name %>
  <%= form_tag(search_results_path, :method => 'get') do %>
    <%= text_field_tag :search, params[:search] %>
    <%= hidden_field_tag :category, @category.id %>
    <button type="submit" type="button">Search</button>
  <% end %>
</div>

<%= link_to 'delete', {action: :destroy}, method: :delete, data: {confirm: "Are you sure?"} %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Wiki</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Businesses", businesses_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Categories", categories_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="container-fluid">
  <%= render 'layouts/header' %>

  <%= yield %>

</div>

</body>
</html>